Pullup ticket 1796 (part 2) - requested by taca security update for php5
Revisions pulled up:
- pkgsrc/lang/php5/Makefile				1.42
- pkgsrc/lang/php5/Makefile.common			1.19
- pkgsrc/lang/php5/distinfo				1.27
- pkgsrc/lang/php5/patches/patch-ao			removed
- pkgsrc/lang/php5/patches/patch-as			1.2
- pkgsrc/lang/php5/patches/patch-at			removed
- pkgsrc/lang/php5/patches/patch-av			removed
- pkgsrc/lang/php5/patches/patch-aw			removed

   Module Name:	pkgsrc
   Committed By:	taca
   Date:		Thu Aug 17 13:17:48 UTC 2006

   Modified Files:
	pkgsrc/lang/php5: Makefile PLIST

   Log Message:
   Correct PLIST to fix a binary package:

   - remove an extra directory.
   - handle empty directories.
---
   Module Name:	pkgsrc
   Committed By:	taca
   Date:		Sat Aug 19 14:47:44 UTC 2006

   Modified Files:
	pkgsrc/lang/php5: Makefile PLIST

   Log Message:
   More fix of PLIST, now pkg_delete should always succeed.
---
   Module Name:	pkgsrc
   Committed By:	taca
   Date:		Sat Aug 19 16:44:15 UTC 2006

   Modified Files:
	pkgsrc/lang/php5: Makefile Makefile.common distinfo
	pkgsrc/lang/php5/patches: patch-as
   Removed Files:
	pkgsrc/lang/php5/patches: patch-ao patch-at patch-av patch-aw

   Log Message:
   Update php5 package to 5.1.5:

   17 Aug 2006, PHP 5.1.5

   - Fixed memory_limit on 64bit systems. (Stefan E.)
   - Fixed overflow on 64bit systems in str_repeat() and wordwrap(). (Stefan E.)
   - Disabled CURLOPT_FOLLOWLOCATION in curl when open_basedir or safe_mode are
     enabled. (Stefan E., Ilia)
   - Fixed bug #38322 (reading past array in sscanf() leads to arbitrary code
     execution). (Tony)
   - Fixed bug #38125 (undefined reference to spl_dual_it_free_storage). (Marcus)
   - Fixed bug #38112 (corrupted gif segfaults) (Pierre)
   - Fixed bug #37587 (var without attribute causes segfault). (Marcus)
   - Fixed bug #37576 (FastCGI env (cgi vars) table overflow). (Piotr)
   - Fixed bug #37496 (FastCGI output buffer overrun). (Piotr, Dmitry)
   - Fixed bug #37487 (oci_fetch_array() array-type should always default to
     OCI_BOTH). (Tony)
   - Fixed bug #37416 (iterator_to_array() hides exceptions thrown in rewind()
     method). (Tony)
   - Fixed bug #37392 (Unnecessary call to OCITransRollback() at the end of
     request). (Tony)
   - Fixed bug #37341 ($_SERVER in included file is shortened to two entries,
     if $_ENV gets used). (Dmitry)
   - Fixed bug #37313 (sigemptyset() used without including <signal.h>).
     (jdolecek)
   - Fixed bug #37346 (invalid colormap format) (Pierre)
   - Fixed bug #37360 (invalid gif size) (Pierre)
   - Fixed bug #37306 (max_execution_time = max_input_time). (Dmitry)
   - Fixed Bug #37278 (SOAP not respecting uri in __soapCall). (Dmitry)
   - Fixed bug #37265 (Added missing safe_mode & open_basedir checks to
  imap_body()). (Ilia)
   - Fixed bug #37256 (php-fastcgi dosen't handle connection abort). (Dmitry)